### ISSUE TITLE
Please respect the cmake variables BUILD_STATIC_LIBS and BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by yurivict** [osqp/osqp#106]
Some users only want shared libs, and some - only static libs. For example, FreeBSD ports generally don't install static libs. Please honor BUILD_STATIC_LIBS and BUILD_SHARED_LIBS.

Please do this in both this and the bundled project.

Thank you.

**Comment by imciner2** [comment]
Support has been added to the `develop-1.0` branch for three new build options:
* `OSQP_BUILD_SHARED_LIB` to enable/disable the building of the shared library
* `OSQP_BUILD_STATIC_LIB` to enable/disable the building of the static library
* `OSQP_BUILD_DEMO_EXE` to enable/disable the building of the demo executable (requires the static library to be built)

These will be included in the future 1.0 release.
