### ISSUE TITLE
Migrate unittests to better framework

### ISSUE THREAD

**Issue by bstellato** [osqp/osqp#141]
A better testing framework would help us a lot. I suggest migrating to CTest (withing cmake) combined with GoogleTest framework. Guidelines [here](https://cliutils.gitlab.io/modern-cmake/chapters/testing.html).

N.B. This is what is currently used in the [osqp-eigen interface](https://github.com/robotology/osqp-eigen).

**Comment by bstellato** [comment]
The unittests output is now too long to be displayed on travis. Fixing this issue would solve the problem and also report useful timings

**Comment by bstellato** [comment]
I have started making changes to migrate to googletest here: https://github.com/oxfordcontrol/osqp/tree/bs/googletest

Note that in this branch I also removed the submodules allowing cmake to download the sources of qdldl and googletest when building the project. I believe it is a cleaner solution to what we are doing now

**Comment by bstellato** [comment]
Another testing framework to consider is [Catch 2](https://github.com/catchorg/Catch2). It is a single-file header-only test framework with all the functionality we need.

**Comment by imciner2** [comment]
I have used Catch2 on another project and it seemed to work well. I also liked that it is single header (so we don't need to do the sub-module shenanigans that google test would need and could just include the single header in the source tree).

**Comment by imciner2** [comment]
The unit tests have now been migrated to Catch2.
