### ISSUE TITLE
Custom timing functions to allow profiling in code generation

### ISSUE THREAD

**Issue by imciner2** [osqp/osqp#153]
It might be a useful thing to allow the user to supply a custom timing function (one that will provide a monotonic tic) if desired on non-Windows/Mac platforms. This way the profiling functions could still be used in the embedded mode if desired (but default to disabled if no custom function is supplied to keep the library-free code structure).

It can probably be implemented in a way similar to the custom memory allocators,  https://github.com/oxfordcontrol/osqp/pull/140. The custom timing function could override the call to `clock_gettime` with the user's function.

Thoughts?

**Comment by imciner2** [comment]
Looking at this a bit more, I am now thinking that it would be best to simply allow the user to provide their own implementation of `osqp_tic` and `osqp_toc` if they want to. This would be done via the cmake route, where they would supply a header that will override the default OSQP-provided functions.

**Comment by goulart-paul** [comment]
How is that different from how we handled #140?

Another approach would be to implement the timing tic/toc as function pointers that are user-reassignable.  If the user asks for EMBEDDED, then we default these to NULL and the user can replace them with anything they want.

We did not implement the memory allocation in that way since they were global functions, but I don't see a problem with having a pair of timing function pointers attached to OSQPWorkspace.

On the other hand, maybe it is best for all of these things to be handled in the same way for the sake of consistency.

**Comment by imciner2** [comment]
@goulart-paul, I think consistency should be an important factor when building these style of interfaces. If someone has to use two different flows for adding in custom override functions it could become confusing.

In comment 2 I was actually saying that instead of having the user override the low-level clock function, they instead just override the osqp timing functions and just provide their own implementation of tic and toc. This would be a similar approach to #140 with the functions `osqp_tic` and `osqp_toc` changed to define statements and the current implementation functions renamed to be `osqp_tic_platform` and `osqp_toc_platform`. Then cmake can default the defines to the correct value of this define for the platform, and for embedded generation the user can supply the defines to their implementation along with the implementation.

I am hopefully going to start prototyping this in the next week or so.

**Comment by goulart-paul** [comment]
@imciner2 OK, I'd be happy with that approach.   I agree that consistency of the interfaces is probably the most important factor here.

**Comment by imciner2** [comment]
A version of this has been merged into the `develop-1.0` branch and will be included in the v1.0 release. All that is left is to document it, but that is tracked by a different issue.
