### ISSUE TITLE
Consolidate `osqp_warm_start` and 'osqp_update_bounds' functionality.

### ISSUE THREAD

**Issue by goulart-paul** [osqp/osqp#192]
Can we just have a single `osqp_warm_start` function? The user can set the variable that need not be updated to `NULL`.

Maybe we can do the same thing for `osqp_update_bounds`.

_Originally posted by @gbanjac in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjgxNjUxMzUw/pull_request_reviews/more_threads_

**Comment by bstellato** [comment]
I agree (the link does not work though)

**Comment by imciner2** [comment]
This has been fixed for 1.0 now and is available in the `develop-1.0` branch.
