### ISSUE TITLE
Passing location of MKL binary

### ISSUE THREAD

**Issue by jd-lara** [osqp/osqp#247]
The manual currently states that if the MKL location is added to the global OS dynamic library paths OSQP detects it manually. How can we pass directly the location of the dynamic libraries? 

For reference, in Julia, we can add to the binaries the MKL binaries as well and it will be useful to be able to specify the MKL library from MKL_jll to be used directly in the solver. 

See discussion here https://github.com/JuliaPackaging/Yggdrasil/pull/846

**Comment by RoyiAvital** [comment]
This is interesting.

If you install `OSQP` under MATLAB, does it use the MKL which is provided by MATLAB?

**Comment by imciner2** [comment]
As of v1.0 beta (on master branch currently), finding the appropriate MKL library is now handled by the linker at compile time and is no longer dlopen'd. Closing this issue.
