### ISSUE TITLE
Migrate CI from Travis/Appveyor to Github actions

### ISSUE THREAD

**Issue by bstellato** [osqp/osqp#284]
Since Travis is significantly reducing the open-source offerings (See [this Julia thread](https://discourse.julialang.org/t/travis-ci-changes-pricing-plans/49528)), I believe we should switch to Github actions. I have performed the migration for the `osqp-python` but the CI of the main repo still needs to be ported.

I would really appreciate if anyone could help migrating the scripts in the [/ci](https://github.com/oxfordcontrol/osqp/tree/master/ci) folder.

**Comment by bstellato** [comment]
Related to reformatting CI: Bintray will close on 01 May 2021. 

We should start attaching artifacts to github releases.

**Comment by imciner2** [comment]
The Appveyor and TravisCI pieces have now been completely removed and replaced with GitHub actions.

**Comment by RoyiAvital** [comment]
Still, there is no place to download the binaries (For example, for MATLAB) from.

**Comment by gbanjac** [comment]
You can find the binaries [here](https://github.com/osqp/osqp-matlab/releases/). If you want to install MATLAB from binaries, try running
```
websave('install_osqp.m','https://raw.githubusercontent.com/osqp/osqp-matlab/master/package/install_osqp.m');
install_osqp
```
