### ISSUE TITLE
OSQP R interface results don't look reasonable.

### ISSUE THREAD

**Issue by studymeow** [osqp/osqp#293]
I am trying to solve quadratic programming in R with package osqp. However, the results looked wrong. I am not where did do things wrong.

The code for reproducing the example attached here:（the objective function is the minimization

```
library(osqp)
library(Matrix)
P <- Matrix(c(1., 0.,0,
              0., 1.,0, 0,0,1), 3, 3, sparse = TRUE)
q <- c(0, 1,1)
A <- Matrix(c(1., 1., 0.,
              1., 0., 1.,1,0,1), 3, 3, sparse = TRUE)
l <- c(1.2, 0., 0.7)
u <- c(2., 0.8, 0.7)
settings <- osqpSettings(alpha = 1.0,eps_abs = 1.0e-05, eps_rel = 1.0e-05,)
model <- osqp(P, q, A, l, u, settings)
res <- model$Solve()

```

This is the output of the model, and it shows the optimal value is 0.7

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Is9Wi.png

However, if use the optimal solution to plug into the objective function it gives me 1.018556

```
#this should be the final objective value after solving
0.5*t(res$x)%*%P%*%res$x+t(c(0,1,1))%*%res$x

#the solution
res$x
#0.6261887 0.3500000 0.3500000

```

More importantly, this is not the optimal solution. If I eyeballed the solution, I could find another answer with a smaller objective function with a value of 0.5,0.1,0.6

Thank you for any advice in advance!

**Comment by gbanjac** [comment]
This is related to [osqp-r](https://github.com/osqp/osqp-r). Please post your issue there.
