### ISSUE TITLE
Enabling static builds for easier distributions of binaries

### ISSUE THREAD

**Issue by henriksjostrom** [osqp/osqp#296]
It would simplify the distribution of binaries that include osqp with MKL for my project if we could compile statically. 

Currently this is not possible as MKL is loaded during runtime.

Would you be willing to add a compile time setting to link it at compile time?

@goulart-paul 

[discussion here](https://osqp.discourse.group/t/static-linking-with-mkl/205)

**Comment by imciner2** [comment]
This is possible now in the version of OSQP on the master branch (what will eventually be 1.0). You can use `-DOSQP_ALGEBRA_BACKEND='mkl' -DMKL_LINK='static'` to get a statically linked OSQP+MKL binary.

Additionally, you can pass `-DMKL_THREADING=<choice>` to change which threading backend MKL will use. (see the upstream MKL CMake documentation for the allowed values for this variable).
