### ISSUE TITLE
GPU Linear System solver

### ISSUE THREAD

**Issue by bstellato** [osqp/osqp#30]
Develop new linear system solver on CUDA GPU.

**Comment by signproduction** [comment]
This would be a game changer.

Do you foresee being able to run the whole process inside the GPU (assuming enough memory), or certain functions would run in the GPU and others in the CPU?

Do you have any idea of when this would be available?  Months?  Years?  Who knows?

Thank you.

**Comment by jbabyhacker** [comment]
@gbanjac Are these changes pushed somewhere?

**Comment by gbanjac** [comment]
Yes, you can find the CUDA implementation in [`cuda-1.0`](https://github.com/oxfordcontrol/osqp/tree/cuda-1.0) branch.

You should compile the code with `CUDA_SUPPORT` flag enabled.

Credits to @micschub.

**Comment by hakeemo** [comment]
@gbanjac is it currently possible to use the GPU through the python interface?

**Comment by gbanjac** [comment]
Yes, you can find the Python interface in this repo: https://github.com/oxfordcontrol/cuosqp

**Comment by hakeemo** [comment]
@gbanjac  is there a way to control the tolerance of the PCG solver? My problem converges with the direct solver on the cpu, but not when using the gpu. I suspect that if I decrease the eps of the PCG solver it would work.

**Comment by gbanjac** [comment]
At the moment, it is not possible to pass the PCG settings externally. However, you can try reducing `CUDA_PCG_REDUCTION_FACTOR` manually in [this file](https://github.com/oxfordcontrol/osqp/blob/cuda-1.0/lin_sys/cuda/cuda_pcg/include/cuda_pcg_constants.h#L34), which corresponds to parameter `lambda` in Section 6.3.3 in [this paper](https://arxiv.org/pdf/1912.04263.pdf).

**Comment by Turoad** [comment]
> We already have a working version, but have to integrate it with the rest of the code in a more structured way. This should probably be available in the following months. It will indeed be a game changer! Initial benchmarks show up to 150x speedup compared to the CPU implementation. We have implemented all the math/algebra on the GPU, not only the linear system solver.

Hi @gbanjac,
Can we run direct direct gpu solve now?  If not, I'm glad to make PRs.
Currently, I'm trying speed up direct cuda by using cuda.  However, I'm sure whether qdldl can be optimized with parallel method. Cound you please give some gudiances.

**Comment by gbanjac** [comment]
Hi @Turoad. We don't have a direct linear system solver running on a GPU at the moment. It would be very much appreciated if you can make a PR.

I would start by looking at the cuSOLVER: https://docs.nvidia.com/cuda/cusolver/index.html

**Comment by lehuyduc** [comment]
@gbanjac hello, I just run OSQP GPU branch `cuda-1.0` on my machine, and it's actually 2x slower on 4000x4000 input matrix. When I run `nvidia-smi`, I also found that GPU usage is basically just 1% (2080ti). On 8000x8000 input matrix, it's only 2x faster.

Could you please upload the case where it's 150x faster than CPU version (as mentioned in your earlier comment) ? Thanks!

**Comment by imciner2** [comment]
We now have a PCG in the CUDA backend of the v1.0.0.beta0 version we just tagged. Closing this issue as completed. Anything else about GPU-based linear solvers should go into new issues with specific details/bugs.
