### ISSUE TITLE
Failed to build with python 2.7

### ISSUE THREAD

**Issue by aaumar** [osqp/osqp#301]
I am trying to use CVXPY for python 2.7 in ubuntu 18 (for ROS melodic project, using python 2.7) and the installation always failed with building osqp. I separately try to install osqp using python 3.6.9 and it is installed. I am wondering is oqsp can be installed for python 2.7? Here is the error message

> (env) aris@aris:~/env/osqp-python$ pip install osqp
.
.
.
.
  [  3%] Building C object lin_sys/direct/qdldl/qdldl_sources/CMakeFiles/qdldlobject.dir/src/qdldl.c.o
  [  3%] Built target qdldlobject
  Scanning dependencies of target linsys_pardiso
  [  6%] Building C object lin_sys/direct/CMakeFiles/linsys_pardiso.dir/pardiso/pardiso_interface.c.o
  [ 10%] Building C object lin_sys/direct/CMakeFiles/linsys_pardiso.dir/pardiso/pardiso_loader.c.o
  [ 10%] Built target linsys_pardiso
  Scanning dependencies of target linsys_qdldl
  [ 13%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_1.c.o
  [ 16%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_2.c.o
  [ 20%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_aat.c.o
  [ 23%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_control.c.o
  [ 26%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_defaults.c.o
  [ 30%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_info.c.o
  [ 33%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_order.c.o
  [ 36%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_post_tree.c.o
  [ 40%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_postorder.c.o
  [ 43%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_preprocess.c.o
  [ 46%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/amd_valid.c.o
  [ 50%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/amd/src/SuiteSparse_config.c.o
  [ 53%] Building C object lin_sys/direct/qdldl/CMakeFiles/linsys_qdldl.dir/qdldl_interface.c.o
  [ 53%] Built target linsys_qdldl
  Scanning dependencies of target osqpstatic
  [ 56%] Building C object CMakeFiles/osqpstatic.dir/src/auxil.c.o
  [ 60%] Building C object CMakeFiles/osqpstatic.dir/src/error.c.o
  [ 63%] Building C object CMakeFiles/osqpstatic.dir/src/lin_alg.c.o
  [ 66%] Building C object CMakeFiles/osqpstatic.dir/src/osqp.c.o
  [ 70%] Building C object CMakeFiles/osqpstatic.dir/src/proj.c.o
  [ 73%] Building C object CMakeFiles/osqpstatic.dir/src/scaling.c.o
  [ 76%] Building C object CMakeFiles/osqpstatic.dir/src/util.c.o
  [ 80%] Building C object CMakeFiles/osqpstatic.dir/src/kkt.c.o
  [ 83%] Building C object CMakeFiles/osqpstatic.dir/src/cs.c.o
  [ 86%] Building C object CMakeFiles/osqpstatic.dir/src/polish.c.o
  [ 90%] Building C object CMakeFiles/osqpstatic.dir/src/lin_sys.c.o
  [ 93%] Building C object CMakeFiles/osqpstatic.dir/src/ctrlc.c.o
  [ 96%] Building C object CMakeFiles/osqpstatic.dir/lin_sys/lib_handler.c.o
  [100%] Linking C static library out/libosqp.a
  [100%] Built target osqpstatic
  building 'osqp._osqp' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/extension
  creating build/temp.linux-x86_64-2.7/extension/src
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-gnDdqE/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYTHON -Iosqp_sources/include -Iosqp_sources/lin_sys/direct/qdldl -Iosqp_sources/lin_sys/direct/qdldl/qdldl_sources/include -Iextension/include -I/tmp/pip-build-env-PJB5GM/overlay/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c extension/src/osqpmodule.c -o build/temp.linux-x86_64-2.7/extension/src/osqpmodule.o -O3
  extension/src/osqpmodule.c:33:16: error: variable ‘moduledef’ has initializer but incomplete type
    static struct PyModuleDef moduledef = {
                  ^~~~~~~~~~~
  extension/src/osqpmodule.c:34:6: error: ‘PyModuleDef_HEAD_INIT’ undeclared here (not in a function); did you mean ‘PyObject_HEAD_INIT’?
        PyModuleDef_HEAD_INIT, "_osqp",       /* m_name */
        ^~~~~~~~~~~~~~~~~~~~~
        PyObject_HEAD_INIT
  extension/src/osqpmodule.c:34:6: warning: excess elements in struct initializer
  extension/src/osqpmodule.c:34:6: note: (near initialization for ‘moduledef’)
  extension/src/osqpmodule.c:34:29: warning: excess elements in struct initializer
        PyModuleDef_HEAD_INIT, "_osqp",       /* m_name */
                               ^~~~~~~
  extension/src/osqpmodule.c:34:29: note: (near initialization for ‘moduledef’)
  extension/src/osqpmodule.c:35:6: warning: excess elements in struct initializer
        NULL,                                 /* m_doc */
        ^~~~
  extension/src/osqpmodule.c:35:6: note: (near initialization for ‘moduledef’)
  extension/src/osqpmodule.c:36:6: warning: excess elements in struct initializer
        -1,                                   /* m_size */
        ^
  extension/src/osqpmodule.c:36:6: note: (near initialization for ‘moduledef’)
  extension/src/osqpmodule.c:37:6: warning: excess elements in struct initializer
        OSQP_module_methods,                  /* m_methods */
        ^~~~~~~~~~~~~~~~~~~
  extension/src/osqpmodule.c:37:6: note: (near initialization for ‘moduledef’)
  extension/src/osqpmodule.c:38:6: warning: excess elements in struct initializer
        NULL,                                 /* m_reload */
        ^~~~
  extension/src/osqpmodule.c:38:6: note: (near initialization for ‘moduledef’)
  extension/src/osqpmodule.c:39:6: warning: excess elements in struct initializer
        NULL,                                 /* m_traverse */
        ^~~~
  extension/src/osqpmodule.c:39:6: note: (near initialization for ‘moduledef’)
  extension/src/osqpmodule.c:40:6: warning: excess elements in struct initializer
        NULL,                                 /* m_clear */
        ^~~~
  extension/src/osqpmodule.c:40:6: note: (near initialization for ‘moduledef’)
  extension/src/osqpmodule.c:41:6: warning: excess elements in struct initializer
        NULL,                                 /* m_free */
        ^~~~
  extension/src/osqpmodule.c:41:6: note: (near initialization for ‘moduledef’)
  extension/src/osqpmodule.c: In function ‘moduleinit’:
  extension/src/osqpmodule.c:50:9: warning: implicit declaration of function ‘PyModule_Create’; did you mean ‘_PyModule_Clear’? [-Wimplicit-function-declaration]
       m = PyModule_Create(&moduledef);
           ^~~~~~~~~~~~~~~
           _PyModule_Clear
  extension/src/osqpmodule.c:50:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
       m = PyModule_Create(&moduledef);
         ^
  extension/src/osqpmodule.c: In function ‘PyInit__osqp’:
  extension/src/osqpmodule.c:77:12: warning: ‘return’ with a value, in function returning void
       return moduleinit();
              ^~~~~~~~~~~~
  extension/src/osqpmodule.c:75:16: note: declared here
   PyMODINIT_FUNC PyInit__osqp(void) {
                  ^~~~~~~~~~~~
  extension/src/osqpmodule.c: At top level:
  extension/src/osqpmodule.c:33:28: error: storage size of ‘moduledef’ isn’t known
    static struct PyModuleDef moduledef = {
                              ^~~~~~~~~
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ERROR: Failed building wheel for osqp
Failed to build osqp
ERROR: Could not build wheels for osqp which use PEP 517 and cannot be installed directly

**Comment by gbanjac** [comment]
As you can see [here](https://github.com/osqp/osqp/releases/tag/v0.6.2), we dropped support for Python 2.7 in release 0.6.2.
