### ISSUE TITLE
The server returned the status 403 with message "Forbidden"

### ISSUE THREAD

**Issue by adil3480** [osqp/osqp#307]
I try to install OSQP from Matlab by running following command
websave('install_osqp.m', 'https://dl.bintray.com/bstellato/generic/OSQP/0.6.2/install_osqp.m');
install_osqp

I receive the following error message: 

Error using websave (line 107)
The server returned the status 403 with message "Forbidden" in response to the
request to URL
https://dl.bintray.com/bstellato/generic/OSQP/0.6.2/install_osqp.m.

Can you please let me know how to fix this issue?

**Comment by adamhe1993** [comment]
I met the same problem. Have you found a solution?

**Comment by grantgib** [comment]
I have the same issue...

**Comment by gbanjac** [comment]
Bintray is shut down. We have updated the link from which you can get `install_osqp.m`. Try running
```
websave('install_osqp.m','https://raw.githubusercontent.com/osqp/osqp-matlab/master/package/install_osqp.m');
install_osqp
```
