### ISSUE TITLE
osqp_demo.c solve status error 

### ISSUE THREAD

**Issue by bostoncleek** [osqp/osqp#313]
Hello, 
I am running `osqp_demo.c` in `examples/` and the solve status is 0.  I was expecting to receive 1.  Perhaps there was a change to the exit codes that is not reflected in the [documentation](https://osqp.org/docs/interfaces/status_values.html).  Either way I took a look at `osqp_solve()` and looks like the exit code should still be set to 1 for proper initialization. @bstellato @traversaro 

**Environment**
- osqp HEAD on master
- Ubuntu 20.04
- gcc 9.3.0

**Comment by imciner2** [comment]
Where are you checking the status? Do you mean the demo executable returns 0 instead of 1, or did you add a check to the return value of the call to `osqp_solve` in the demo executable?

**Comment by bostoncleek** [comment]
The call to the function `osqp_solve()` returns 0. I added a print statement bellow [line 43](https://github.com/osqp/osqp/blob/master/examples/osqp_demo.c#L43).

**Comment by imciner2** [comment]
The solver function `osqp_solve()` does not return the solver status, the status is contained inside the `workspace->info->status_val` field (with the string representation in the `workspace->info->status` field). It looks like the return is simply a flag when some of the things failed (but it isn't `1` for every non-solve status).

**Comment by bostoncleek** [comment]
@imciner2 My misunderstanding, thank you for the clarification.
