### ISSUE TITLE
MPC example in python and cvxpy

### ISSUE THREAD

**Issue by queezus** [osqp/osqp#322]
Hi, 

I am learning about MPC and optimization and wanted to test the example MPC code provided on the osqp website. When I did this, the optimal objectives returned from the python code were negative. I am under the impression that because the objective function is a QP the optimal objectives should be positive. I then tried to test the cvxpy code and got positive optimal objectives, but they are completely different from the ones in the python code.

I am confused as to why (1) the python code results in a negative optimal objective and (2) why the python and cvxpy codes return different results. Any insight into these question would be much appreciated.

**Comment by imciner2** [comment]
Convexity of the cost function doesn't mean that the cost function is guaranteed to be positive - it just means that there will be a single local optimum that is also the global optimum. The function could still be negative - take for instance the cost function x^2-5, this function is convex and the optimum cost will be -5 (at x=0).

As for the OSQP vs cvxpy, can you please provide the example code you are using?

**Comment by queezus** [comment]
I see that makes sense. Thank You.

Here is the link for the code:

https://osqp.org/docs/examples/mpc.html

**Comment by queezus** [comment]
Last MPC iteration using python:
![image](https://user-images.githubusercontent.com/89816536/131570455-ae19066e-7994-46fd-b4b1-6c3dd7156fa0.png)

All 15 MPC iterations using cvxpy:
![image](https://user-images.githubusercontent.com/89816536/131571000-f8467bf4-d4f1-4035-9435-084f60f59c76.png)

**Comment by queezus** [comment]
Last MPC iteration using python:
![image](https://user-images.githubusercontent.com/89816536/131729676-2b01e472-2a31-4be4-bffa-8b061bb67931.png)

All 15 MPC iterations using cvxpy:
The optimal objectives printed using "print(res)"
![image](https://user-images.githubusercontent.com/89816536/131729712-7fb36fff-f2d5-49e3-b724-5d963e1dac5f.png)

**Comment by gbanjac** [comment]
You are seeing different objective values because you have terms in the objective function of the form `(x_k-x_r)' Q (x_k-x_r)`, which is equal to `x_k' Q x_k - 2 x_k' Q x_r + x_r ' Q x_r`. The first term is quadratic in variable `x_k`, the second is linear, and the third is constant. The objective function of OSQP has the form `1/2 x' P x + q' x`, that is, it does not take constant terms, while CVXPY includes these constant terms in the objective value.
