### ISSUE TITLE
Version header file is missing

### ISSUE THREAD

**Issue by Garfield753** [osqp/osqp#323]
When building the current master from source (cmake 3.10.2, ubuntu 18), the file `version.h` does not get installed/copied.

Commands:
~~~
cd ~
mkdir osqp_ws
cd osqp_ws
git clone --recursive https://github.com/oxfordcontrol/osqp
cd osqp
mkdir build
cd build
cmake -G "Unix Makefiles" ..
make -j
sudo make install
~~~

The file `cmake_install.cmake` which is generated in the build folder lists a bunch of headers except `version.h`:

~~~
...
if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/osqp" TYPE FILE FILES
    "/home/ubuntu18/osqp_ws/osqp/include/auxil.h"
    "/home/ubuntu18/osqp_ws/osqp/include/constants.h"
    "/home/ubuntu18/osqp_ws/osqp/include/error.h"
    "/home/ubuntu18/osqp_ws/osqp/include/glob_opts.h"
    "/home/ubuntu18/osqp_ws/osqp/include/lin_alg.h"
    "/home/ubuntu18/osqp_ws/osqp/include/osqp.h"
    "/home/ubuntu18/osqp_ws/osqp/include/osqp_configure.h"
    "/home/ubuntu18/osqp_ws/osqp/include/proj.h"
    "/home/ubuntu18/osqp_ws/osqp/include/scaling.h"
    "/home/ubuntu18/osqp_ws/osqp/include/types.h"
    "/home/ubuntu18/osqp_ws/osqp/include/util.h"
    "/home/ubuntu18/osqp_ws/osqp/include/cs.h"
    "/home/ubuntu18/osqp_ws/osqp/include/polish.h"
    "/home/ubuntu18/osqp_ws/osqp/include/lin_sys.h"
    "/home/ubuntu18/osqp_ws/osqp/include/ctrlc.h"
    )
endif()
...
~~~

When adding `"/home/ubuntu18/osqp_ws/osqp/include/version.h"`  to the file by hand it installs fine. However, the stored version number does not seem to be correct (if that is critical):

~~~
/**
This file is replaced by an auto-generated version.h
with an OSQP_VERSION obtained from a variable supplied
to cmake
*/

#ifndef OSQP_VERSION
#define OSQP_VERSION "0.0.0"
#endif
~~~

This may be related to recent changes in #316.

**Comment by vineetbansal** [comment]
@Garfield753 - thanks for pointing out the bug! We've fixed this in the master branch now. The stored version you see (0.0.0) is indeed 'correct' in this case since you're building from source. When pulling pre-released libraries of OSQP from Github in the future, the version number will be populated correctly.

I'm closing this issue. Feel free to open it again in case we've missed something.
