### ISSUE TITLE
Broken link of related paper of MIOSQP

### ISSUE THREAD

**Issue by yasirroni** [osqp/osqp#329]
Paper for MIOSQP no longer available in https://stellato.io/assets/downloads/publications/2018/miosqp_ecc.pdf. Maybe maintainer should reupload the paper or mirror to other source such as http://cse.lab.imtlucca.it/~bemporad/publications/papers/ecc18-miosqp.pdf

**Comment by gbanjac** [comment]
Fixed via https://github.com/osqp/osqp/commit/de8dab2c081ead84a1cc890c296f646fd26dc339 and https://github.com/osqp/osqp/commit/b0cc0e8d08efcebeb5d9728a0cee4a0de4fdb809
