### ISSUE TITLE
Documentation on including osqp algebras in cmake 

### ISSUE THREAD

**Issue by vineetbansal** [osqp/osqp#354]
We should have an example on how to use cmake with osqp mkl/cuda algebras (involves linking to mkl/cuda currently, though that can be burnt into the osqp:: namespace using interface targets). This would be the ideal place for it:

https://osqp.org/docs/get_started/C.html

**Comment by imciner2** [comment]
This is now included in https://github.com/osqp/osqp/issues/444.
