### ISSUE TITLE
Prefix OSQP cmake constants with OSQP_

### ISSUE THREAD

**Issue by vineetbansal** [osqp/osqp#355]
Everything in osqp_configure.h.in that is 
#cmakedefine SOMETHING Should become #cmakedefine OSQP_SOMETHING

**Comment by imciner2** [comment]
More of the constants have been changed over to have an `OSQP_` prefix in #445, however there still are several remaining, including:
* `ALGEBRA`
* `DFLOAT`
* `DLONG`
* `DEBUG`
* `EMBEDDED`

**Comment by imciner2** [comment]
The only one remaining now is the `DEBUG` constants.

**Comment by imciner2** [comment]
The `DEBUG` constant was removed and instead the CMake build type is used to trigger a debug build. This means all CMake constants have been namespaced in 1.0.
