### ISSUE TITLE
[OSQP 1.0] MKL algebra development

### ISSUE THREAD

**Issue by gbanjac** [osqp/osqp#358]
- use `mkl_sparse_?_mv` for matrix-vector multiplications; this requires using the MKL matrix handle
- get rid of OSQP API calls within MKL algebra functions; use internal MKL functions instead. This will remove the need for `OSQPVectorf_view_update()` as it is currently only used in `mkl-cg_interface.c`.

**Comment by imciner2** [comment]
The MKL matrix-vector operations have been implemented in https://github.com/osqp/osqp/pull/440.
