### ISSUE TITLE
Issues using mutli-thread to solve independent QP problems via OSQP

### ISSUE THREAD

**Issue by xinbada007** [osqp/osqp#363]
Hello everyone, I currently use osqp 0.6.2 in my cpp project.

Say I have multiple (1~4) independent QP problems. For the sake of efficiency, I have coded multi-thread to solve them simultaneously. Specifically, I have wrapped osqp into a class without any static member or shared variable, so each thread starts with its own instance of the class and has its own osqp settings, osqp data, osqp workspace, etc. 

The thing is:
1, Once in multi-thread mode, I can't use ctrl-c to terminate the whole program. Of course, ctrl-c works with multi-thread if osqp is not called. As long as osqp is not called, I can use ctrl-c with the same multi-thread settings.

2, With multi-thread, osqp occasionally throws KKT failed and the whole program crashed. Of course, with single-thread, I have literally tested overnight with OSQP.

**Comment by goulart-paul** [comment]
Regarding 2: Which linear system solver are you using within each of the OSQP instances?   If it is QDLDL then it is hard to understand what is going on, but MKL Pardiso could (?) require more care than we currently employ.

I would suggest opening the 1 first item as a separate issue, since these seem like unrelated problems.

**Comment by xinbada007** [comment]
> Regarding 2: Which linear system solver are you using within each of the OSQP instances? If it is QDLDL then it is hard to understand what is going on, but MKL Pardiso could (?) require more care than we currently employ.
> 
> I would suggest opening the 1 first item as a separate issue, since these seem like unrelated problems.

I'm using QDLDL. My colleagues and I have been trying various ways in making ctrl-c work in multi-thread with OSQP. We just found that if we lock "osqp_setup" and "osqp_solve", ctrl-c works and no KKT failed. The working code is like this:

static std::mutex mx;
mx.lock();
osqp_setup(blah, blah, blah);
mx.unlock();

...

mx.lock();
osqp_solve(blah);
mx.unlock();

However, this is basically single-thread.

Should I submit another issue describing the first item?

**Comment by goulart-paul** [comment]
> Should I submit another issue describing the first item?

Yes please.

**Comment by goulart-paul** [comment]
You can compile OSQP with the ctrl-c behaviour disable using `-DCTRLC=OFF` from cmake.   Does KKT fail when multithreading solvers if you do that?

**Comment by xinbada007** [comment]
> You can compile OSQP with the ctrl-c behaviour disable using `-DCTRLC=OFF` from cmake. Does KKT fail when multithreading solvers if you do that?

Just tried that, with no luck. Still, get KKT failure with no lock. And found that I actually need to lock anywhere that generates data for osqp (such as the code for cost function matrix, constraints matrix, etc.). So the code be like this:
mutex.lock();

generate_cost_matrix();
generate_contraints_matrix();
generate_boundaries_matrix();

make_them_sparse();
put_them_in_osqp_data();

osqp_setup();
osqp_solve();

mutex.unlock();

To summary, I get KKT failure without this lock, and I get success with this lock (exactly the same settings, the same QP problem).

**Comment by goulart-paul** [comment]
How about if you only apply the lock during the setup phase, but not the solve?   Perhaps it is a memory allocation issue, and the solve phase should not be allocating any memory.

**Comment by xinbada007** [comment]
> How about if you only apply the lock during the setup phase, but not the solve? Perhaps it is a memory allocation issue, and the solve phase should not be allocating any memory.

It works (for at least 1 hour, no KKT failure, and ctrl-c works). But anything related to "work (OSQPWorkspace* work)" needs to be locked, except osqp_solve. I have locked osqp_setup, osqp_warm_start_x, osqp_cleanup.

**Comment by goulart-paul** [comment]
If I understand correctly (also based on discussion in in #366), the issue is the use of a non-threadsafe malloc / printf.     If that completely explains it then I suggest to close both issues.

**Comment by xinbada007** [comment]
Please close both issues. 

Sorry for that. It may not be an OSQP issue, a couple of hours ago, I found our own bug ( a static var was used in a function that does Double Compare) which causes corrupted data when generating sparse matrix in multi-thread env. After fix, I found NO ISSUE when running OSQP WITHOUT LOCK in multi-thread env. The malloc and printf are indeed thread-safe (they use locks inside their implementation) but are not async-signal-safe, which I am still trying hard to understand. Anyway, the bug does seem unrelated to OSQP.
