### ISSUE TITLE
Cannot terminate (ctrl-c) OSQP in multi-thread mode

### ISSUE THREAD

**Issue by xinbada007** [osqp/osqp#366]
Hello everyone, I currently use osqp 0.6.2 with qdldl in my cpp project.

Say I have multiple (1~4) independent QP problems. For the sake of efficiency, I have coded multi-thread to solve them simultaneously. Specifically, I have wrapped osqp into a class without any static member or shared variable, so each thread starts with its own instance of the class and has its own osqp settings, osqp data, osqp workspace, etc.

The thing is, once in multi-thread mode, I can't use ctrl-c to terminate the whole program. As long as osqp is not called, I can use ctrl-c with the same multi-thread settings, and of course ctrl-c works with osqp in single-thread mode.

P.S: spent one day trying different ways, finding that if we **lock and only lock** osqp_setup() and osqp_solve(), ctrl-c works with osqp in multi-thread mode.

Any ideas?

**Comment by xinbada007** [comment]
Found the reason:

see https://stackoverflow.com/questions/3941271/why-are-malloc-and-printf-said-as-non-reentrant.

osqp heavily uses malloc(), free(), and printf(), which are all non-reentrant and not safe in async multi-thread environment.

If one needs to run osqp in multi-thread, one needs to do the following things:

Disable all "printf" function in osqp, including "disable ctrl-c (it prints)" and "disable printing at all" in its CMakeLists.

After all this, it should be safe to **ONLY** release lock to osqp_solve(), not the others!

**Comment by goulart-paul** [comment]
Version 1.0, which is in development still but will be released quite soon, supports user-specifiable memory management.   Hopefully that will be useful to you.

**Comment by sshawn9** [comment]
> Version 1.0, which is in development still but will be released quite soon, supports user-specifiable memory management. Hopefully that will be useful to you.

Will version 1.0 finally come out some day?
