### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by lovebugayy** [osqp/osqp#372]
I'm trying install osqp. when in the build file, when I type
cmake .. -DBUILD_SHARED_LIBS=ON
then,the terminal will return an error with:
/osqp/lin_sys/direct/qdldl/qdldl_sources

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!

**Comment by bstellato** [comment]
Did you clone with the `--recursive` option as mentioned in the [docs](https://osqp.org/docs/get_started/sources.html#build-the-binaries)?

**Comment by goulart-paul** [comment]
Not having had a reply here, I will close this since the suggestion of @bstellato seems likely to fix the problem.   Please reopen if that doesn't fix it.
