### ISSUE TITLE
primal infeasible solution does not converge

### ISSUE THREAD

**Issue by sichaozhang1112** [osqp/osqp#381]
hello all,
i've encountered this problem when osqp returned "primal infeasible" with following log, and i found the solution becomes larger along iterations and fails to converge. What can be the reason causes the solution approach such large value?

```
  problem:  variables n = 163, constraints m = 655
            nnz(P) + nnz(A) = 2282
  settings: linear system solver = qdldl,
            eps_abs = 1.0e-03, eps_rel = 1.0e-03,
            eps_prim_inf = 1.0e-03, eps_dual_inf = 1.0e-04,
            rho = 1.00e-01 (adaptive),
            sigma = 1.00e-06, alpha = 1.60, max_iter = 500
            check_termination: on (interval 25),
            scaling: on, scaled_termination: on
            warm start: on, polish: on, time_limit: off
  
  iter   objective    pri res    dua res    rho        time
     1  -9.5845e+00   7.17e+00   7.20e+02   1.00e-01   5.38e-04s
   200  -1.2538e+02   1.84e-01   1.42e-03   1.00e-01   2.48e-03s
   325   1.0000e+30   1.85e-01   4.04e-03   5.30e-01   3.72e-03s
  
  status:               primal infeasible
  number of iterations: 325
  run time:             3.73e-03s
  optimal rho estimate: 1.46e+00
```

**Comment by goulart-paul** [comment]
Are you sure that the problem you are passing to the solver is actually feasible?   The solver reports 'primal infeasible' only when it is able to compute an infeasible certificate, i.e. a proof that there is no decision variable that is consistent with the constraints you set.

**Comment by sichaozhang1112** [comment]
I'm not 100% sure about the feasibility, but it can be solved by acado. I will check it later. Is it normal that the solution x becomes larger along iterations when problem is primal infeasible?

**Comment by sichaozhang1112** [comment]
thank you. the problem is solved when i set small max_iteration (50) and improve the discretized model, and the solution is acceptable.
