### ISSUE TITLE
Unable to compile: how to deal with a missing header file?

### ISSUE THREAD

**Issue by willi7758521** [osqp/osqp#382]
![image](https://user-images.githubusercontent.com/98402190/151391887-ed8ffa6d-846e-47ed-84d3-e020b6ccd8c4.png)

**Comment by goulart-paul** [comment]
The file `osqp_configure` should be auto generated by cmake.  Are you using cmake to generate your project?

**Comment by willi7758521** [comment]
Oh, I'll try it with cmake. Thank you
