### ISSUE TITLE
Is the matrix in the osqp_demo.c inconsistent with the example matrix on the official website?

### ISSUE THREAD

**Issue by willi7758521** [osqp/osqp#384]
the matrix in the osqp_demo.c is :
![image](https://user-images.githubusercontent.com/98402190/151561408-16400e9c-4f71-4b7f-b0ec-1730e875a2d9.png)
when I try to convert it from csc format to general style, it becomes:
![image](https://user-images.githubusercontent.com/98402190/151562353-bbce7284-b278-4dc2-a865-305fc5fea12c.png)
which is different with the official website:
![image](https://user-images.githubusercontent.com/98402190/151562582-8d0959f8-b33e-4b06-b1b0-a3516d3f2ebf.png)
Is my conversion wrong?or else ?

my conversion steps are as follows:
the first col have the nonzero element : P_x[0]=4, it's row number is  0; so (0,0)=4 , (1,0)=0;
the second col have two element : P_x[1] and P_x[2] , whose row number is 0 and 1; so (0,1)=1 , (1,1)=2 ;

**Comment by goulart-paul** [comment]
The solver only takes the upper triangular part of the data as input.   The lower triangular part is assumed to be symmetric.
