### ISSUE TITLE
Update linked cuda toolkit to 11.6

### ISSUE THREAD

**Issue by vineetbansal** [osqp/osqp#391]
The OSQP `gpu` runner is currently building `ALGEBRA=cuda` against CUDA Toolkit 11.2. This toolkit is only compatible with gcc 10, which means on the runner we're using:

```
cmake_flags: ['-DBUILD_TESTING=ON -DALGEBRA=cuda -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_CUDA_HOST_COMPILER=g++-10']
```

Moving code from 11.2 to 11.6 (current as of 2/7/22) will probably entail some refactoring (names in the `Thrust::` namespace seem to have been moved around).

**Comment by imciner2** [comment]
@vineetbansal I just checked, and apparently I have CUDA 11.6 on my dev machine, and it can compile the CUDA algebra version of the library with no error. So I don't think there will be any refactoring needed, just updating the CI.

**Comment by vineetbansal** [comment]
@imciner2 - yes - I've changed the soft-link (`/usr/local/cuda`) in the runner to point to 11.6 instead of the 11.2 initially and everything still seems to work. Let's keep this open for now. I think the issue may have been Windows-specific.

**Comment by vineetbansal** [comment]
@imciner2 - the CUDA version on the gpu runner is 11.6, and we're building the cuda python wheels (the `osqp-cuda` package) on CUDA 11.6 on both Windows and Linux, and both are compiling fine. I'm closing this for now.
