### ISSUE TITLE
How to improve the accuracy of OSQP（Eigen-osqp）?

### ISSUE THREAD

**Issue by qinwenchuang** [osqp/osqp#392]
I converted all the constraints in the test set to -inf<= Gx <= r format for verification. According to the comparison results, it is found that the result of OSQP does not meet the expectation. Is this the problem of my test?

**_Problem			qpOASES			OSQP		
Name	nV	nC	Time/s	max_error	norm_error	Time/s	max_error	norm_error_**
**CVXQP1_S**	100	300	0.070813	1.47E-14	4.62E-14	0.105993	0.0241871	0.0569613
**CVXQP2_S**	100	250	0.044548	1.55E-14	4.31E-14	0.021414	0.00770127	0.0105453
**CVXQP3_S**	100	350	0.080688	2.81E-12	6.47E-12	0.04644	0.0502566	0.137518
**DPKLO1**	133	420	0.130113	4.04E-14	1.34E-13	0.053876	0.0137307	0.0354173
**DUAL1**	85	172	0.013882	1.04E-15	3.14E-15	0.006569	0.000625404	0.00195075
**DUAL2**	96	194	0.014682	1.02E-16	3.30E-16	0.008867	2.69E-05	8.79E-05
**DUAL3**	111	224	0.024222	6.59E-17	2.96E-16	0.012753	4.98E-05	0.000190497
**DUAL4**	75	152	0.007408	1.92E-16	8.48E-16	0.003828	7.41E-05	0.000210997
**DUALC1**	9	448	0.001282	1.94E-15	2.22E-15	0.035532	0.0829243	0.119989
**DUALC2**	7	472	0.001403	1.11E-16	1.24E-16	0.029177	0.312781	0.357861
**DUALC5**	8	572	0.000533	1.11E-16	1.34E-16	0.039215	0.134035	0.166892
**DUALC8**	8	1022	0.002818	1.99E-10	2.46E-10	0.066776	0.0823098	0.113531
**GENHS28**	10	36	0.000108	8.05E-16	1.27E-15	0.000148	5.97E-05	9.24E-05
**HS118**	15	64	0.000349	6.22E-15	7.23E-15	0.000779	0.394111	0.77042
**HS21**	2	6	2.50E-05	5.55E-17	5.55E-17	5.00E-05	1.66E-05	1.66E-05
**HS268**	5	20	7.30E-05	7.19E-11	1.10E-10	5.90E-05	1.72454	2.1079
**HS35**	3	8	3.50E-05	1.11E-16	1.24E-16	2.90E-05	7.76E-06	8.34E-06
**HS35MOD**	3	8	3.20E-05	2.22E-16	3.14E-16	2.20E-05	0.000592292	0.000651054
**HS51**	5	16	3.10E-05	2.44E-15	4.57E-15	4.10E-05	0.00234377	0.00412887
**HS52**	5	16	4.40E-05	2.22E-16	2.64E-16	4.70E-05	0.000585878	0.000699181
**HS53**	5	16	4.00E-05	2.22E-16	2.94E-16	4.60E-05	0.000599737	0.00107456
**HS76**	4	14	6.30E-05	1.11E-16	1.14E-16	4.20E-05	0.000354457	0.000390567
**LOTSCHD**	12	38	0.000226	3.77E-13	6.99E-13	0.000265	0.234805	0.326846
**PRIMALC1**	230	478	0.454913	1551.2	1551.76	1.25603	717349	717349
**PRIMALC2**	231	476	0.426533	961.038	961.126	1.14638	234629	234629
P**RIMALC5**	287	590	0.72547	7652.7	7652.7	1.72055	9539.87	9539.87
**QADLITTL**	97	306	0.107402	34	79.1461	0.037149	60.8574	135.272
**QAFIRO**	32	118	0.00226	44.936	66.9834	0.002126	20.3286	30.604
**QBEACONF**	262	870	0.501426	2793.08	5718.99	2.33043	1175.25	1769.56
**QBRANDY**	249	938	0.592477	3533.29	4041.25	0.895891	922.213	1053.49
**QE226**	282	1010	0.73309	111.249	165.234	2.26622	53.5426	79.5175
**QISRAEL**	142	632	0.24701	6048.78	19510.1	0.791599	11220.7	38510.4
**QPCBLEND**	83	314	0.038042	1.04E-14	1.52E-14	0.019101	0.00260095	0.00459251
**QPCBOEI2**	143	618	0.190723	4.14E-11	7.34E-11	0.757896	300.922	596.24
**QPTEST**	2	8	4.10E-05	1.11E-16	1.24E-16	3.90E-05	1.81E-05	1.81E-05
**QRECIPE**	180	542	0.257768	3.20E-14	9.21E-14	0.099193	6.7435	24.2543
**QSC205**	203	816	0.410162	3.63E-11	1.27E-10	0.320703	0.238189	0.844383
**QSCAGR7**	140	538	0.274525	2701.14	9627.23	0.162509	1980.18	4622.22
**QSHARE1B**	225	684	0.46376	889508	910527	1.58215	889325	923133
**QSHARE2B**	79	350	0.07954	3.53238	7.41892	0.234934	7.0586	13.5626
**S268**	5	20	8.20E-05	7.19E-11	1.10E-10	7.20E-05	1.72454	2.1079
**TAME**	2	6	1.90E-05	1.11E-16	1.11E-16	2.10E-05	1.12E-06	1.58E-06
**VALUES**	202	406	0.176507	0.425502	1.79664	0.111526	0.271706	0.8365
**ZECEVIC2**	2	8	5.00E-05	1.11E-16	1.11E-16	3.90E-05	0.000254865	0.000254865

**Comment by goulart-paul** [comment]
It looks like you are using the Maros Meszaros test yet.   I would suggest starting from the source files [here](https://github.com/osqp/osqp_benchmarks) since they have already been put into OSQP friendly format.

Note that that test set has some quite difficult examples, so don't expect that OSQP will solve all of them.

**Comment by qinwenchuang** [comment]
Thanks for your reply, I think I know how to use it better.
