### ISSUE TITLE
Diverge At Iteration 500

### ISSUE THREAD

**Issue by sichaozhang1112** [osqp/osqp#398]
Hello all,
I've encountered this interesting phenomenon, that for the same problem, osqp solution will diverge at iteration 500. if i set max_iter as 500, it would be like:
```
  settings: linear system solver = qdldl,
            eps_abs = 1.0e-03, eps_rel = 1.0e-03,
            eps_prim_inf = 1.0e-03, eps_dual_inf = 1.0e-04,
            rho = 1.00e-01 (adaptive),
            sigma = 1.00e-06, alpha = 1.60, max_iter = 500
            check_termination: on (interval 25),
            scaling: on, scaled_termination: on
            warm start: on, polish: on, time_limit: off
  
  adaptive_rho_interval = 0
  iter   objective    pri res    dua res    rho        time
     1  -1.8411e+02   1.73e+01   5.72e+02   1.00e-01   6.82e-04s
   200  -9.8386e+02   5.03e-02   2.21e-03   1.00e-01   3.56e-03s
   400  -9.8398e+02   5.03e-02   3.87e-04   1.00e-01   6.29e-03s
   500   1.0000e+30   5.03e-02   1.89e-04   1.00e-01   7.63e-03s
  
  status:               primal infeasible
  number of iterations: 500
  run time:             7.65e-03s
  optimal rho estimate: 3.37e-01
```

if I set max_iter as 250 (did not osqp_setup every time, but osqp_update): 
```
  iter   objective    pri res    dua res    rho        time
     1  -1.8411e+02   1.73e+01   5.72e+02   1.00e-01   2.75e-04s
   200  -9.8386e+02   5.03e-02   2.21e-03   1.00e-01   3.20e-03s
   250  -9.8393e+02   5.03e-02   1.36e-03   1.00e-01   3.92e-03s
  
  status:               solved inaccurate
  number of iterations: 250
  optimal objective:    -983.9313
  run time:             3.94e-03s
  optimal rho estimate: 1.26e-01
  
  iter   objective    pri res    dua res    rho        time
     1  -9.8393e+02   5.03e-02   1.35e-03   1.00e-01   2.80e-04s
   200  -9.8398e+02   5.03e-02   2.69e-04   1.00e-01   3.15e-03s
   250   1.0000e+30   5.03e-02   1.89e-04   1.00e-01   3.92e-03s
  
  status:               primal infeasible
  number of iterations: 250
  run time:             3.94e-03s
  optimal rho estimate: 3.37e-01
```

Iteration 50, 100 are also tried. It looks like that solution diverge at exact the 500th iteration, but it has converged already as you can see. 
Hope someone can explain. Appreciate it.

**Comment by goulart-paul** [comment]
I would tend to believe the "primal infeasibility" result there.   What is happening is that the solver has determined from successive iterations that it could construct an infeasibility certificate, i.e. a proof that the problem can't be solved.   It even reports this certificate to you in the solution (i.e. the "solution" in that case is instead the certificate itself).

Halting earlier and getting a "solved inaccurate" state is more like the solver just saying "this solution looks kind of close and I've hit the iteration limit, so maybe".

**Comment by sichaozhang1112** [comment]
Thanks for you reply, prof. Goulart.
What i understand here is solution has converged already but the residuals cannot reach the threshold that i set, therefore, it hit the iteration limit. But the solution becomes an unacceptable large number after certain iterations (after several calculation) is what confused me.

**Comment by goulart-paul** [comment]
Are you absolutely certain that your problem is feasible?   It could be the case that the solver is getting to a nearly feasible point but then the iterates diverge because the problem is not actually solvable.

Without seeing an actual example it is hard to diagnose.      Either way, the problem is perhaps better discussed on the OSQP forum here: https://osqp.discourse.group/

**Comment by sichaozhang1112** [comment]
okay understand. Thank you~~
