### ISSUE TITLE
Why this QP problem can't be solved

### ISSUE THREAD

**Issue by Syk-yr** [osqp/osqp#399]
P=[2 0 0 0 0 0 0 0 0 0 0 0 
0 2 0 0 0 0 0 0 0 0 0 0 
0 0 2 0 0 0 0 0 0 0 0 0 
0 0 0 2 0 0 0 0 0 0 0 0 
0 0 0 0 1 0 0 0 0 0 0 0 
0 0 0 0 0 1 0 0 0 0 0 0 
0 0 0 0 0 0 1 0 0 0 0 0 
0 0 0 0 0 0 0 1 0 0 0 0 
0 0 0 0 0 0 0 0 26 -50 0 0 
0 0 0 0 0 0 0 0 0 51 -50 0 
0 0 0 0 0 0 0 0 0 0 51 -50 
0 0 0 0 0 0 0 0 0 0 0 26 ]
can't be solved
"ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex
ERROR in osqp_setup: KKT matrix factorization.
The problem seems to be non-convex."

and 
P=[2 0 0 0 0 0 0 0 0 0 0 0 
0 2 0 0 0 0 0 0 0 0 0 0 
0 0 2 0 0 0 0 0 0 0 0 0 
0 0 0 2 0 0 0 0 0 0 0 0 
0 0 0 0 1 0 0 0 0 0 0 0 
0 0 0 0 0 1 0 0 0 0 0 0 
0 0 0 0 0 0 1 0 0 0 0 0 
0 0 0 0 0 0 0 1 0 0 0 0 
0 0 0 0 0 0 0 0 2.7 -3.6 0 0 
0 0 0 0 0 0 0 0 0 4.6 -3.6 0 
0 0 0 0 0 0 0 0 0 0 4.6 -3.6 
0 0 0 0 0 0 0 0 0 0 0 2.7 ]
can be solved
status:               solved
number of iterations: 175
optimal objective:    -2.7307
run time:             4.81e-03s
optimal rho estimate: 6.30e-01

**Comment by goulart-paul** [comment]
I assume that you are showing here only the upper triangular part of the `P` matrix.   The solver is telling you exactly what the problem is : namely, your P matrix has a negative eigenvalue and your problem is therefore not convex.   OSQP is only intended for convex optimisation problems.

Note that the first example has one eigenvalue that is `= -38.04`.

**Comment by Syk-yr** [comment]
Thank you vary much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Paul ***@***.***&gt;; 
发送时间: 2022年2月28日(星期一) 晚上10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [osqp/osqp] Why this QP problem can&#39;t be solved (Issue #399)






我假设您在这里只显示了P矩阵解算器告诉你问题是什么：也就是说，你的 P 矩阵有一个负的特征值，因此你的问题不是凸的。OS QP 只用于凸优化问题。

请注意，第一个示例有一个特征值，即= -38.04.

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;
