### ISSUE TITLE
NaN values in solution when replacing OSQP with cuOSQP

### ISSUE THREAD

**Issue by camilogonzalez97** [osqp/osqp#424]
I have been using OSQP as part of another library to solve an MPC problem. My goal is to implement a controller that can run at 100 Hz, but at present solving the problem takes ~55ms and I can only get it down to ~50ms when I decrease the prediction and control horizons to values that don't even work for my application. This led me to try cuOSQP but I am having trouble using this as a replacement for OSQP.

I am using the [cuda-1.0](https://github.com/osqp/osqp/tree/cuda-1.0) branch on Windows and my CUDA toolkit version is 11.6. I can run the demo program without issues. But when I try to solve the same MPC problem I was solving with OSQP the solution is always filled with NaNs. The issue pops up after the very first iteration where the objective is somehow 0. 

![image](https://user-images.githubusercontent.com/17459590/172303073-9d50a220-539a-4d15-9f25-8b57e3409bc2.png)

I have tried checking if I am injecting any NaNs by accident but don't think that is the case. I am giving `osqp_setup` the same matrices as I did before for OSQP. I have no clue where the problem is coming from - debugging suggestions would be very much appreciated.

**Comment by camilogonzalez97** [comment]
Thank you for getting back to me. I have been using the C interface for both OSQP and cuOSQP and I believe I am giving the function `ospq_setup` the same input in both cases. The only difference is that cuOSQP takes the inputs `P, q, A l, u, m, n` separately, while in OSQP those inputs are passed bundled in a OSQPData instance. In cuOSQP the OSQPData struct consists of different types like `OSQPMatrix` and `OSQPVectorf` but `osqp_setup` still expects `csc*` and `c_float*` which in my case was convenient because the library I am modifying already converts to those types. This conversion starts with an Eigen sparse matrix and uses `csc_spalloc` from the cuOSQP API to eventually convert to a `csc*`. The implementation of `csc_spalloc` is the same in cuOSQP and OSQP so the conversion step _should_ be unaffected.

That being said, you are probably right about the mangling because for my problem nnz(P) = 1936 and nnz(A)= 8160. I'm not sure what that means but they are definitely not the same.  

I will dig some more and maybe check what nnz(P) and nnz(A) I had before when using OSQP. I suppose I should also find a way to actually check that all inputs to `osqp_setup` are the same. Is there anything else you suggest I check? 

Thank you for your help!

**Comment by camilogonzalez97** [comment]
I have now verified that P and A are the same for OSQP and cuOSQP. When I use OSQP the nnz counts for P and A are still different (nnz(P) = 1936 and nnz(A)= 8160) but the problem is solved without issues. Is it typically necessary to have nnz(P) = nnz(A)?

I don't understand how setting P = 0 would help the nnz counts. After I tried it nnz(P) became 0 and nnz(A) is still 8160. The solver runs but I just get NaN in the output as before. 

Is it possible that the data is not being copied to the GPU? I am using Visual Studio and don't seem to be able to read most of the memory of the P and A matrices after they are converted to `OSQPMatrix` instances. Could it be that I am missing some basic configuration of CUDA?

**Comment by goulart-paul** [comment]
I suggested setting P = 0 only because a mismatch on nnz(P) is the most common problem.   The reason is that OSQP is expecting only the upper triangular part of a symmetric matrix there, and a mismatch often means that the user has passed the whole thing.

It should not be the case that nnz(P) = nnz(A) in general.

I suppose that a CUDA config problem is also possible, but it's hard to say.   Have you tried solving a really small problem, like a 2x2 QP or similar?

**Comment by camilogonzalez97** [comment]
The osqp_demo runs successfully without NaNs and is using the cuda pcg solver. I copied the demo's code into the library I am modifying and it still runs successfully so I don't think its a configuration error anymore. 

So... I have verified that I'm solving the same problem in OSQP and cuOSQP (same matrices in both cases) and there seems to be no configuration issue. Is there a reason why cuOSQP would not be able to solve a problem that OSQP can?

**Comment by camilogonzalez97** [comment]
Yeap, it was mangled data all along... 
Turns out the problem was not the matrices - it was the `l` and `u` vectors which when cast from `double` to `float` contained NaNs and Inf. For some reason even if there were no NaNs in the vectors the Inf casting from `double` to `float` still resulted in NaN output. Modifying my application to work with floats only solved the problem.

The issue that I now face is that cuOSQP returns completely different solutions compared to those of OSQP and it takes thousands of iterations to solve the problem compared to <100 in OSQP... I suppose I have some more digging to do, but my original problem is solved. Thank you for all the help @goulart-paul.
