### ISSUE TITLE
Broken link for miOSQP paper

### ISSUE THREAD

**Issue by imciner2** [osqp/osqp#507]
The link for miOSQP on the docs citing page is not working anymore. It is pointing to https://stellato.io/downloads/publications/2018/miosqp_ecc.pdf, but that is giving a 404.

@bstellato what is the open-access URL for this paper now?

**Comment by bstellato** [comment]
Hi @imciner2 thanks for pointing this out. The URL now has: `access/` in front:

https://stellato.io/assets/downloads/publications/2018/miosqp_ecc.pdf

Would you mind fixing this in the docs?
