### ISSUE TITLE
OSQP v1.0.0beta1 is not able to compile under clang 16.0.6 on Arch Linux

### ISSUE THREAD

**Issue by houchen-li** [osqp/osqp#586]
# Description
I am trying to use OSQP v1.0.0beta1 to build up my own project on Arch Linux. As part of the compatibility requirement, my project need to be built with both gcc and clang compiler. Under gcc 13.2.1, OSQP works out. But as it comes to clang 16.0.6, an compile error shows up when compiling OSQP. It seems to be a function pointer mismatch error.

# Info
> algebra/_common/lin_sys/qdldl/qdldl_interface.c:242:27: error: incompatible function pointer types assigning to 'OSQPInt (*)(struct qdldl *)' (aka 'int (*)(struct qdldl *)') from 'OSQPInt (*)(qdldl_solver *, const OSQPMatrix *, const OSQPMatrix *, const OSQPMatrix *, const OSQPMatrix *, const OSQPVectorf *, const OSQPVectorf *)' (aka 'int (*)(struct qdldl *, const struct OSQPMatrix_ *, const struct OSQPMatrix_ *, const struct OSQPMatrix_ *, const struct OSQPMatrix_ *, const struct OSQPVectorf_ *, const struct OSQPVectorf_ *)') [-Wincompatible-function-pointer-types]
> [build]     s->adjoint_derivative = &adjoint_derivative_qdldl;
> [build]                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by imciner2** [comment]
This is already fixed in our development branch in https://github.com/osqp/osqp/commit/56b6dfe5a50217a93f5cecc9e92978069cf43a5c, and will be part of the next beta release.
