### ISSUE TITLE
hpipm codegen fails on Windows

### ISSUE THREAD

**Issue by jgillis** [osqp/osqp#617]
`inline` makes the compiler (mingw gcc) complain about missing symbols

**Comment by imciner2** [comment]
@jgillis did you mean to open this for OSQP? The title says hpipm in it.

**Comment by jgillis** [comment]
No I meant hpipm. Osqp should work fine: some students used it in my class today, on Windows.

**Comment by jgillis** [comment]
Im very sorry, wrong repo. Not aure how this happened.
