### ISSUE TITLE
Compatibility of OSQP Library with 32-bit Embedded Devices : Erroneous results

### ISSUE THREAD

**Issue by lordmendonca** [osqp/osqp#620]
**Background:**
I want to use the OSQP library to implement Moving Horizon Estimation for a specific application. I have been successful in using it in MATLAB/SIMULINK. Now I want to implement its equivalent C-code implementation on a 32-bit target device.

I have generated the C code using the OSQP code generator on MATLAB with the parameter configuration as 'MATRICES' (EMBEDDED_MODE = 2).

**Issue:**
When testing the C-code generated for a 32-bit target device, it does not give a result equivalent to that of results in MATLAB/SIMULINK. In fact, it is erroneous.

**Observation:**
1. When I test the code generated for a 64-bit target device, it matches the results obtained in MATLAB/SIMULINK.
2. Having generated code for single-precision and double-precision, the only difference in the code that was generated lies in 'osqp_configure.h' and 'qdldl_types.h' where float is changed to double.
- Single precision:
![image](https://github.com/osqp/osqp/assets/113859302/b54a3f81-a6ec-44e1-9c9e-7b242bb6246e)
- Double precision:
![image](https://github.com/osqp/osqp/assets/113859302/f8bfb6da-017f-4c18-ab44-8476a060b648)

**Question:**
Is this library compatible with 32-bit embedded devices with sufficient accuracy?

**Artefacts:**
Result from MATLAB/SIMULINK:
![image](https://github.com/osqp/osqp/assets/113859302/b9abc48a-9e73-40af-84ad-226fd6904432)

Result from configuration as single precision in C (Matrix has been transposed here):
![image](https://github.com/osqp/osqp/assets/113859302/5306e645-7edc-4d8e-8408-904026fdd146)

Build warnings when using single precision in C:
![image](https://github.com/osqp/osqp/assets/113859302/b879381f-87d4-4d85-825e-f093f499e02f)

Result from configuration as double precision in C (Matrix has been transposed here):
![image](https://github.com/osqp/osqp/assets/113859302/2c3b057a-a3b5-4904-8638-6e8534f85b86)

**Comment by imciner2** [comment]
Good to hear you figured this out, and sorry for not replying earlier. One thing to note is that the single precision (32-bit) version of the solver may require longer to solve the problem, and also may not necessarily reach a high tolerance (e.g. you probably don't want to put a tolerance beyond around 1e-5 for the single precision, whereas a double precision solver would be able to go higher), just because of the rounding errors that occur during the computations.

**Comment by lordmendonca** [comment]
Thanks for the response and information. I will keep it in mind.
