### ISSUE TITLE
Osqp-eigen without including eigen library. Is it possible?

### ISSUE THREAD

**Issue by WestsideMS** [osqp/osqp#649]
I am trying to implement MPC code using osqp-eigen, but I am wondering if it is essential to include the eigen library like #include <Eigen/Dense>.

I am wondering if the code cannot be implemented using only osqp-eigen without including the eigen library.

The reason I'm asking is because I thought there might be a way to use only OSQP eigen without using the eigen library when embedding.

**Comment by traversaro** [comment]
Hello @WestsideMS , please do not cross-post (see https://github.com/orgs/osqp/discussions/650).

**Comment by WestsideMS** [comment]
Hello @traversaro . Sorry about that. Please delete this issue because I cannnot delete this one. There's no option in top-right dot.
