### ISSUE TITLE
(on cuda-1.0 branch)Cross-compiling executable files for the ARMv8 platform on the x86 platform

### ISSUE THREAD

**Issue by layman163** [osqp/osqp#668]
Hi, I would like to use the cuda-1.0 branch. Due to resource constraints, I have to cross-compile for my ARMv8 platform on the x86 platform. 
I added the following commands to CMakeLists:
`set(CMAKE_LINKER /usr/bin/aarch64-linux-gnu-ld)
set(CMAKE_ASM_COMPILER /usr/bin/aarch64-linux-gnu-as)
set(CMAKE_AR /usr/bin/aarch64-linux-gnu-ar)
set(CMAKE_RANLIB /usr/bin/aarch64-linux-gnu-ranlib)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER /usr/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/aarch64-linux-gnu-g++)`
But I found that for some reason, cmake calls the regular g++. 
The reason might be that the link.cpp file generated the following instructions.
![image](https://github.com/user-attachments/assets/ed443d2f-cb65-4752-9375-2305d602d144)
 Could you please tell me how to resolve this, or if there is a more convenient way to accomplish my requirement? Thank you for your help.

**Comment by imciner2** [comment]
How are you passing the new toolchain? Did you create a dedicated CMake toolchains file and then specify that on the command line - e.g. https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling? That is generally the best way to handle cross-compiling, because all these variables need to be set before the OSQP CMake project is declared and setup.

**Comment by layman163** [comment]
> How are you passing the new toolchain? Did you create a dedicated CMake toolchains file and then specify that on the command line - e.g. https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling? That is generally the best way to handle cross-compiling, because all these variables need to be set before the OSQP CMake project is declared and setup.

**Comment by layman163** [comment]
> How are you passing the new toolchain? Did you create a dedicated CMake toolchains file and then specify that on the command line - e.g. https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling? That is generally the best way to handle cross-compiling, because all these variables need to be set before the OSQP CMake project is declared and setup.

thank you very much. It may be caused by my path error
