### ISSUE TITLE
exported symbols and namespace issues

### ISSUE THREAD

**Issue by mlubin** [osqp/osqp#67]
Both [OSQP](https://github.com/oxfordcontrol/osqp/blob/bb5bb360b6dee9725256cb6953c774a82520edda/include/auxil.h#L107) and [ECOS](https://github.com/embotech/ecos/blob/14e89089c76a99648e01b63c9503df7e3360271e/ecos_bb/ecos_bb.c#L239) define and export a function called `store_solution` with a signature that's basically identical at the linking level. I discovered this by watching `osqp_solve` crash with a stack trace that pointed to ECOS...

I'm not familiar with all of the subtleties of visibility issues in C libraries, but I think the following defensive proposal would prevent issues like this:

(Proposal) Functions defined by OSQP should be either:
1. prefixed with `osqp_`, or
2. marked as `static`, and hence only visible within a single .c file.

If ECOS followed this proposal, the issue would've been avoided since their version of `store_solution` can be marked `static`.

What do you think?

**Comment by bstellato** [comment]
C can be a real pain with these namespaces. What about having

* Functions defined in `osqp.h` with the prefix `osqp_` (already done)
* All the other internal functions `static`

I am pretty sure it could work despite small bugs that might appear by making some of the functions static.

**Comment by mlubin** [comment]
`static` means that the function is only visible within a single source file, but there may be internal OSQP functions that would be useful to have available in multiple files. A possible naming convention for these functions is an underscore at the end. So I'd update the proposal as follows:

(Proposal) Functions defined by OSQP should be one of:

1. (public API) prefixed with `osqp_`, e.g., `osqp_solve`
2. (internal API used across files) prefixed with `osqp_` and postfixed with an underscore, e.g., `osqp_store_solution_`
2. (internal API within a file) marked as static, e.g., `static void* csc_malloc`.

**Comment by bstellato** [comment]
I have made a few changes to the function names according to 2. Let me know what you think @mlubin. 

I agree on points 1 and 2. However, after thinking about it, I am not sure how the `static` name functions like `csc_malloc` could work.  If you make these functions static, they are only visible within a single file. I am not sure the program would even compile. The alternative would be to move the linear algebra functions to headers (Eigen-style) that are included in each file. This could unnecessarily increase the binary file dimension by replicating many functions.

@goulart-paul @gbanjac What do you think?

**Comment by mlubin** [comment]
I suggested `csc_malloc` because from what I can tell it's not declared in any header files and is only used in cs.c, so I'd expect it to compile with `static`.

**Comment by traversaro** [comment]
If I understood correctly the problem, an alternative solution to prevent symbol collision for the private functions is mark with [symbol visibility attributes](https://gcc.gnu.org/wiki/Visibility) only  the functions in the public API. This would have the nice lateral effect to make the shared library build usable in Windows.

**Comment by mlubin** [comment]
I'm not familiar with those visibility attributes, but it could be worth looking into.

**Comment by bstellato** [comment]
@traversaro thank you for the suggestion! I will definitely look into that. It seems a much cleaner way to fix this issue.

**Comment by traversaro** [comment]
In this case, you may be interested in the [`GenerateExportHeader`](https://cmake.org/cmake/help/v3.5/module/GenerateExportHeader.html) CMake module. 

See this issue: https://github.com/ros/console_bridge/pull/40#issuecomment-269460721 for a bit of context.

**Comment by imciner2** [comment]
See #210 for more namespace conflicts.

**Comment by imciner2** [comment]
All of these namespace conflicts should be fixed in the master branch now (what will become 1.0).
