### ISSUE TITLE
osqp-mkl version is not giving any results

### ISSUE THREAD

**Issue by yeasmin62** [osqp/osqp#680]
I am using following code to check whether **osqp-mkl** works or not. If I install **basic osqp** following code works but if I install **osqp-mkl** , it doesn't show print any result and doesn't show any error. could you please tell me what is the problem?
I have installed the osqp-mkl on the python version 3.9.16. 

**Is there any prerequisite to make it working?**

```
import osqp
import numpy as np
from scipy import sparse

# Define a simple QP problem
P = sparse.csc_matrix([[4, 1], [1, 2]])
q = np.array([1, 1])
A = sparse.csc_matrix([[1.0, 1.0], [1.0, 0.0]])
l = np.array([1.0, 0.0])
u = np.array([1.0, 0.7])

# Set up the OSQP problem
prob = osqp.OSQP()
prob.setup(P, q, A, l, u, verbose=True,time_limit=5.0)

# Solve the problem
res = prob.solve()

# Print results
print("Status:", res.info.status)
print("Optimal solution:", res.x)
print("Objective value:", res.info.obj_val)

```

**Comment by vineetbansal** [comment]
@yeasmin62 - can you open up this issue in the `osqp-python` repository since it's related to the python wrappers for osqp? Thanks.

**Comment by yeasmin62** [comment]
The problem is solved after adding the mkl libraries and cmake path into environmental variable
