### ISSUE TITLE
LP Solver

### ISSUE THREAD

**Issue by ng5** [osqp/osqp#92]
Hi,

If Q matrix is set to 0, will ADMM algorithm automatically fallback to LP algorithms like Simplex.

Reason i'm asking this is to avoid using another library like Coin OR clp if osqp already implements LP solver automatically.

I can publish LP solver benchmark if you can please confirm this is implemented.

Regards,
Rohit

**Comment by goulart-paul** [comment]
OSQP does not require a positive definite quadratic cost.   Q can be any semidefinite matrix, including Q = 0.

We do not use a different solution strategy in the particular case Q = 0.   The OSQP algorithm is the same in any case and will still converge.

On 24 Sep 2018, at 13:23, Rohit Vishwakarma <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

If Q matrix is set to 0, will ADMM algorithm automatically fallback to LP algorithms like Simplex.

Reason i'm asking this is to avoid using another library like Coin OR clp if osqp already implements LP solver automatically.

I can publish LP solver benchmark if you can please confirm this is implemented.

Regards,
Rohit

**Comment by gbanjac** [comment]
For general questions related to OSQP you could use our [forum](https://groups.google.com/forum/#!forum/osqp). Thanks.
